### ISSUE TITLE
Issue when spawning server 

### ISSUE THREAD

**Issue by laurensdv** [jcrist/skein#142]
Hello,

when starting Jupyterhub with Yarnspawner and skein underneith. 
There is an uncaught exception that results in a very bad ERROR 500 in Jupyterhub upon starting the server with the yarnspawner.

The stacktrace goes very deep in the skein code. Any ideas on the cause?

```bash
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 1052, in get
        await self.spawn_single_user(user)
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 705, in spawn_single_user
        timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 626, in finish_user_spawn
        await spawn_future
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 489, in spawn
        raise e
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 409, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/opt/anaconda3/lib/python3.6/site-packages/yarnspawner/spawner.py", line 197, in start
        spec = self._build_specification()
      File "/opt/anaconda3/lib/python3.6/site-packages/yarnspawner/spawner.py", line 170, in _build_specification
        security=security
      File "/opt/anaconda3/lib/python3.6/site-packages/skein/model.py", line 1034, in __init__
        if files is not None else {})
      File "/opt/anaconda3/lib/python3.6/site-packages/skein/model.py", line 1033, in <dictcomp>
        for (k, v) in files.items()}
      File "/opt/anaconda3/lib/python3.6/site-packages/skein/model.py", line 593, in __init__
        self._assign_required('source', source)
      File "/opt/anaconda3/lib/python3.6/site-packages/skein/objects.py", line 146, in _assign_required
        setattr(self, name, val)
      File "/opt/anaconda3/lib/python3.6/site-packages/skein/model.py", line 617, in source
        raise context.TypeError("'source' must be a string")
    TypeError: 'source' must be a string
```

**Comment by jcrist** [comment]
You need yarnspawner's master branch for the current docs to work. I should probably just make a new release. For now you can install yarnspawner from github as follows:

```
pip install -U git+https://github.com/jcrist/yarnspawner.git
```

Alternatively you could change the config to:

```python
c.YarnSpawner.localize_files = {
    'environment': 'hdfs:///path/to/environments/environment.tar.gz',
}
```

and it would work with the current release.

**Comment by laurensdv** [comment]
Hello,

Yes this indeed fixes the issue!

KR
