### ISSUE TITLE
How to properly define programmatic `depends` statement for services

### ISSUE THREAD

**Issue by gallamine** [jcrist/skein#143]
Hello, I'm defining a service in Python (for Dask YARN) and I'm trying to set up a correct `depends` clause so my workers start after my scheduler. The documentation says that the `depends` field for a service is `A set of service names that this service depends on`. I've tried defining my application like this but I get an error:

```WORKER_INSTANCES = 8
WORKER_MEMORY = "12 GiB"
WORKER_VCORES = 4
SCHEDULER_MEMORY = "4 GiB"
SCHEDULER_VCORES = 1

worker = skein.Service(
    instances=WORKER_INSTANCES,
    max_restarts=-1,
    resources=skein.Resources(
        memory=WORKER_MEMORY,
        vcores=WORKER_VCORES
    ),
    script='dask-yarn services worker',
    depends='dask.scheduler'
)

scheduler = skein.Service(
    resources=skein.Resources(
        memory=SCHEDULER_MEMORY,
        vcores=SCHEDULER_VCORES
    ),
    script='dask-yarn services scheduler'
)

spec = skein.ApplicationSpec(
    name='appname',
    queue='default',
    services={
        'dask.worker': worker,
        'dask.scheduler': scheduler
    }
)

cluster = YarnCluster.from_specification(spec)
```

however I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/azkaban_projects/ovforecast/projects/de_ghd_ovf/forecast/ovf.py", line 294, in forecast_
    testset, custom_group_file, use_yarn=use_yarn)
  File "/usr/local/lib/python2.7/site-packages/ovforecast/forecast.py", line 85, in forecast
    reset_loggers=True)
  File "/usr/local/lib/python2.7/site-packages/functools32/functools32.py", line 400, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/ovforecast/yarn.py", line 266, in get_dask_cluster
    'dask.scheduler': scheduler
  File "/usr/local/lib/python2.7/site-packages/skein/model.py", line 1176, in __init__
    self._validate()
  File "/usr/local/lib/python2.7/site-packages/skein/model.py", line 1205, in _validate
    "%s" % (name, format_list(missing)))
ValueError: Unknown service dependencies for service 'dask.worker':
```

How should I be defining the service name for the dependency?

**Comment by jcrist** [comment]
The error message you copied wasn't the full error message. Here's the full error:

```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-b55176f20be2> in <module>
     28     services={
     29         'dask.worker': worker,
---> 30         'dask.scheduler': scheduler
     31     }
     32 )

~/Code/skein/skein/model.py in __init__(self, services, master, name, queue, user, node_label, tags, file_systems, acls, max_attempts)
   1174         self.acls = ACLs() if acls is None else acls
   1175         self.max_attempts = max_attempts
-> 1176         self._validate()
   1177
   1178     def __repr__(self):

~/Code/skein/skein/model.py in _validate(self)
   1203                 raise context.ValueError(
   1204                     "Unknown service dependencies for service %r:\n"
-> 1205                     "%s" % (name, format_list(missing)))
   1206
   1207         dependencies = {name: service.depends

ValueError: Unknown service dependencies for service 'dask.worker':
- .
- a
- c
- d
- e
- h
- k
- l
- r
- s
- u
```

The issue here is that you want to provide `"A *set* of service names that this service depends on"`, and you've provided a string. Try `depends=['dask.scheduler']`

Our error message could definitely be more informative though, currently we just call `set` on depends (which converts the string into a set of characters), which is why you get the uninformative error above.

**Comment by gallamine** [comment]
Thanks! That worked. Should have paid closer attention to what object type was being cast to a `set`.
