### ISSUE TITLE
[Yarn HA] Skein trying to connect to standby node

### ISSUE THREAD

**Issue by zlanka** [jcrist/skein#177]
```
19/06/10 12:19:13 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/06/10 12:19:14 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
19/06/10 12:19:14 INFO impl.TimelineClientImpl: Timeline service address: http://hs-0001:8188/ws/v1/timeline/
19/06/10 12:19:15 INFO skein.Driver: Driver started, listening on 42301
19/06/10 12:19:15 INFO impl.TimelineClientImpl: Timeline service address: http://hs-0001:8188/ws/v1/timeline/
19/06/10 12:19:15 INFO client.ConfiguredRMFailoverProxyProvider: Failing over to rm2
19/06/10 12:19:15 INFO retry.RetryInvocationHandler: Exception while invoking getNewApplication of class ApplicationClientProtocolPBClientImpl over rm2 after 1 fail over attempts. Trying to fail over after sleeping for 34195ms.
java.net.ConnectException: Call From gw/X.X.X.X to rm-0002:8032 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:792)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:732)
	at org.apache.hadoop.ipc.Client.call(Client.java:1431)
	at org.apache.hadoop.ipc.Client.call(Client.java:1358)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
	at com.sun.proxy.$Proxy22.getNewApplication(Unknown Source)
	at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationClientProtocolPBClientImpl.getNewApplication(ApplicationClientProtocolPBClientImpl.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy23.getNewApplication(Unknown Source)
	at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.getNewApplication(YarnClientImpl.java:220)
	at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.createApplication(YarnClientImpl.java:228)
	at com.anaconda.skein.Driver.submitApplicationInner(Driver.java:357)
	at com.anaconda.skein.Driver.access$200(Driver.java:71)
	at com.anaconda.skein.Driver$3.run(Driver.java:344)
	at com.anaconda.skein.Driver$3.run(Driver.java:342)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
	at com.anaconda.skein.Driver.submitApplication(Driver.java:341)
	at com.anaconda.skein.Driver$DriverImpl.submit(Driver.java:891)
	at com.anaconda.skein.DriverGrpc$MethodHandlers.invoke(DriverGrpc.java:565)
	at com.anaconda.skein.shaded.io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at com.anaconda.skein.shaded.io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
	at com.anaconda.skein.shaded.io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
	at com.anaconda.skein.shaded.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at com.anaconda.skein.shaded.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:531)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:495)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:612)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:710)
	at org.apache.hadoop.ipc.Client$Connection.access$2800(Client.java:373)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1493)
	at org.apache.hadoop.ipc.Client.call(Client.java:1397)
	... 31 more
^CTraceback (most recent call last):
  File "/grid/1/conda/bin/dask-yarn", line 10, in <module>
    sys.exit(main())
  File "/grid/1/conda/lib/python3.7/site-packages/dask_yarn/cli.py", line 407, in main
    func(**kwargs)
  File "/grid/1/conda/lib/python3.7/site-packages/dask_yarn/cli.py", line 207, in submit
    app_id = skein_client.submit(spec)
  File "/grid/1/conda/lib/python3.7/site-packages/skein/core.py", line 508, in submit
    resp = self._call('submit', spec.to_protobuf())
  File "/grid/1/conda/lib/python3.7/site-packages/skein/core.py", line 281, in _call
    return getattr(self._stub, method)(req, timeout=timeout)
  File "/grid/1/conda/lib/python3.7/site-packages/grpc/_channel.py", line 564, in __call__
    wait_for_ready, compression)
  File "/grid/1/conda/lib/python3.7/site-packages/grpc/_channel.py", line 552, in _blocking
    event = call.next_event()
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 310, in grpc._cython.cygrpc.SegregatedCall.next_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 150, in grpc._cython.cygrpc._next_call_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi", line 67, in grpc._cython.cygrpc._latent_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi", line 46, in grpc._cython.cygrpc._next
KeyboardInterrupt
19/06/10 12:19:25 INFO skein.Driver: Driver shut down
```

**Comment by jcrist** [comment]
YARN is a bit odd with that - the above exception may be a sign of an issue with our code, but it may be innocuous - when YARN failover occurs the underlying Java libraries still log the error message before failing over. We don't do anything specific for handling HA, but AFAICT per the YARN docs we shouldn't need too. Was everything working properly at this time (no RM outage?) Does this error always occur when submitting an application?
