### ISSUE TITLE
SSL error when launching

### ISSUE THREAD

**Issue by quartox** [jcrist/skein#183]
- **A description of the bug**

Can't launch skein driver. I had an error last year related to the tmp directory that was causing netty problems. I tried it both with and without the tmpdir option on.

- **Steps to reproduce** 

`skein driver start` or starting a `YarnCluster` instance in python.

Previously I needed to specify `skein.Client(java_options='-Djava.io.tmpdir=/path/to/tmp')`

Which yields a slightly different SSL error.

```
19/07/29 13:47:54 INFO skein.Driver: Driver started, listening on 39848
E0729 13:47:54.691855802   67297 ssl_transport_security.cc:1229] Handshake failed with fatal error SSL_ERROR_SSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed.
```

- **Relevant logs/tracebacks**

With the java_options, python traceback

```
---------------------------------------------------------------------------
ConnectionError                           Traceback (most recent call last)
<ipython-input-1-01ab5e0a82ce> in <module>
     25 os.environ['CLASSPATH'] = completed_process.stdout
     26 
---> 27 skein_client = skein.Client(java_options='-Djava.io.tmpdir=/nas/isg_prodops_work/gusto/tmp')
     28 
     29 # Create a cluster where each worker has two cores and eight GiB of memory

/nas/isg_prodops_work/jlord/conda/envs/dask-nlp/lib/python3.7/site-packages/skein/core.py in __init__(self, address, security, keytab, principal, log, log_level, java_options)
    364         try:
    365             # Ping server to check connection
--> 366             self._call('ping', proto.Empty())
    367         except Exception:
    368             if proc is not None:

/nas/isg_prodops_work/jlord/conda/envs/dask-nlp/lib/python3.7/site-packages/skein/core.py in _call(self, method, req, timeout)
    287         code = exc.code()
    288         if code == grpc.StatusCode.UNAVAILABLE:
--> 289             raise ConnectionError("Unable to connect to %s" % self._server_name)
    290         if code == grpc.StatusCode.DEADLINE_EXCEEDED:
    291             raise TimeoutError("Unable to connect to %s" % self._server_name)

ConnectionError: Unable to connect to driver
```

Using `skein driver start --log-level debug --log mylog.txt`

```
19/07/29 13:36:45 DEBUG skein.Driver: Starting Skein version 0.7.4
19/07/29 13:36:45 DEBUG skein.Driver: Logging in using ticket cache
19/07/29 13:36:47 INFO internal.NativeLibraryLoader: {} exists but cannot be executed even when execute permissions set; check volume for "noexec" flag; use -Di
o.netty.native.workdir=[path] to set native working directory separately.
Jul 29, 2019 1:36:47 PM com.anaconda.skein.shaded.io.grpc.netty.GrpcSslContexts defaultSslProvider
INFO: netty-tcnative unavailable (this may be normal)
java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_64, netty_tcnative_linux_x86_64_fedora, netty_tcnative_
x86_64, netty_tcnative]
	at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:104)
	at com.anaconda.skein.shaded.io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:440)
	at com.anaconda.skein.shaded.io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:97)
	at com.anaconda.skein.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:244)
	at com.anaconda.skein.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
	at com.anaconda.skein.shaded.io.grpc.netty.GrpcSslContexts.forServer(GrpcSslContexts.java:151)
	at com.anaconda.skein.Driver.startServer(Driver.java:123)
	at com.anaconda.skein.Driver.run(Driver.java:284)
	at com.anaconda.skein.Driver.main(Driver.java:174)
	Suppressed: java.lang.UnsatisfiedLinkError: /tmp/libcom_anaconda_skein_shaded_netty_tcnative_linux_x86_648974974763192655999.so: /tmp/libcom_anaconda_sk
ein_shaded_netty_tcnative_linux_x86_648974974763192655999.so: failed to map segment from shared object: Operation not permitted
		at java.lang.ClassLoader$NativeLibrary.load(Native Method)
		at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
		at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
		at java.lang.Runtime.load0(Runtime.java:809)
		at java.lang.System.load(System.java:1086)
		at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
		at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:316)
		at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:215)
		at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
		... 8 more
		Suppressed: java.lang.UnsatisfiedLinkError: /tmp/libcom_anaconda_skein_shaded_netty_tcnative_linux_x86_648974974763192655999.so: /tmp/libcom_ana
conda_skein_shaded_netty_tcnative_linux_x86_648974974763192655999.so: failed to map segment from shared object: Operation not permitted
			at java.lang.ClassLoader$NativeLibrary.load(Native Method)
			at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
			at java.lang.Runtime.load0(Runtime.java:809)
			at java.lang.System.load(System.java:1086)
			at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.lang.reflect.Method.invoke(Method.java:498)
			at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:336)
			at java.security.AccessController.doPrivileged(Native Method)
			at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:328)
			at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:306)
			... 10 more
		Suppressed: java.lang.UnsatisfiedLinkError: no com_anaconda_skein_shaded_netty_tcnative_linux_x86_64 in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
			at java.lang.Runtime.loadLibrary0(Runtime.java:870)
			at java.lang.System.loadLibrary(System.java:1122)
			at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:316)
			at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
			... 9 more
			Suppressed: java.lang.UnsatisfiedLinkError: no com_anaconda_skein_shaded_netty_tcnative_linux_x86_64 in java.library.path
				at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
				at java.lang.Runtime.loadLibrary0(Runtime.java:870)
				at java.lang.System.loadLibrary(System.java:1122)
				at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.lang.reflect.Method.invoke(Method.java:498)
				at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:336)
				at java.security.AccessController.doPrivileged(Native Method)
				at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:328)
				at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:306)
				... 10 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: com_anaconda_skein_shaded_netty_tcnative_linux_x86_64_fedora
		at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:233)
		at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
		... 8 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libcom_anaconda_skein_shaded_netty_tcnative_linux_x86_64_fedora.so
		at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:173)
		... 9 more
		Suppressed: java.lang.UnsatisfiedLinkError: no com_anaconda_skein_shaded_netty_tcnative_linux_x86_64_fedora in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
			at java.lang.Runtime.loadLibrary0(Runtime.java:870)
			at java.lang.System.loadLibrary(System.java:1122)
			at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:316)
			at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
			... 9 more
			Suppressed: java.lang.UnsatisfiedLinkError: no com_anaconda_skein_shaded_netty_tcnative_linux_x86_64_fedora in java.library.path
				at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
				at java.lang.Runtime.loadLibrary0(Runtime.java:870)
				at java.lang.System.loadLibrary(System.java:1122)
				at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.lang.reflect.Method.invoke(Method.java:498)
				at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:336)
				at java.security.AccessController.doPrivileged(Native Method)
				at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:328)
				at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:306)
				... 10 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: com_anaconda_skein_shaded_netty_tcnative_x86_64
		at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:233)
		at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
		... 8 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libcom_anaconda_skein_shaded_netty_tcnative_x86_64.so
		at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:173)
		... 9 more
		Suppressed: java.lang.UnsatisfiedLinkError: no com_anaconda_skein_shaded_netty_tcnative_x86_64 in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
			at java.lang.Runtime.loadLibrary0(Runtime.java:870)
			at java.lang.System.loadLibrary(System.java:1122)
			at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:316)
			at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
			... 9 more
			Suppressed: java.lang.UnsatisfiedLinkError: no com_anaconda_skein_shaded_netty_tcnative_x86_64 in java.library.path
				at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
				at java.lang.Runtime.loadLibrary0(Runtime.java:870)
				at java.lang.System.loadLibrary(System.java:1122)
				at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.lang.reflect.Method.invoke(Method.java:498)
				at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:336)
				at java.security.AccessController.doPrivileged(Native Method)
				at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:328)
				at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:306)
				... 10 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: com_anaconda_skein_shaded_netty_tcnative
		at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:233)
		at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
		... 8 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libcom_anaconda_skein_shaded_netty_tcnative.so
		at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:173)
		... 9 more
		Suppressed: java.lang.UnsatisfiedLinkError: no com_anaconda_skein_shaded_netty_tcnative in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
			at java.lang.Runtime.loadLibrary0(Runtime.java:870)
			at java.lang.System.loadLibrary(System.java:1122)
			at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:316)
			at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
			... 9 more
			Suppressed: java.lang.UnsatisfiedLinkError: no com_anaconda_skein_shaded_netty_tcnative in java.library.path
				at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
				at java.lang.Runtime.loadLibrary0(Runtime.java:870)
				at java.lang.System.loadLibrary(System.java:1122)
				at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.lang.reflect.Method.invoke(Method.java:498)
				at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:336)
				at java.security.AccessController.doPrivileged(Native Method)
				at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:328)
				at com.anaconda.skein.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:306)
				... 10 more

Jul 29, 2019 1:36:47 PM com.anaconda.skein.shaded.io.grpc.netty.GrpcSslContexts defaultSslProvider
INFO: Conscrypt not found (this may be normal)
Jul 29, 2019 1:36:47 PM com.anaconda.skein.shaded.io.grpc.netty.GrpcSslContexts defaultSslProvider
INFO: Jetty ALPN unavailable (this may be normal)
java.lang.ClassNotFoundException: com/anaconda/skein/shaded/org/eclipse/jetty/alpn/ALPN
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.anaconda.skein.shaded.io.grpc.netty.JettyTlsUtil.isJettyAlpnConfigured(JettyTlsUtil.java:64)
	at com.anaconda.skein.shaded.io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:266)
	at com.anaconda.skein.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:248)
	at com.anaconda.skein.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
	at com.anaconda.skein.shaded.io.grpc.netty.GrpcSslContexts.forServer(GrpcSslContexts.java:151)
	at com.anaconda.skein.Driver.startServer(Driver.java:123)
	at com.anaconda.skein.Driver.run(Driver.java:284)
	at com.anaconda.skein.Driver.main(Driver.java:174)

19/07/29 13:36:47 ERROR skein.Driver: Error running Driver
java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
	at com.anaconda.skein.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:258)
	at com.anaconda.skein.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
	at com.anaconda.skein.shaded.io.grpc.netty.GrpcSslContexts.forServer(GrpcSslContexts.java:151)
	at com.anaconda.skein.Driver.startServer(Driver.java:123)
	at com.anaconda.skein.Driver.run(Driver.java:284)
	at com.anaconda.skein.Driver.main(Driver.java:174)
```

- **Version information**

    - Python version: 3.7
    - Hadoop version, and distribution (e.g. CDH) if applicable: 2.6.0-cdh5.13.3
    - Skein version: 0.7.4

**Comment by jcrist** [comment]
Without the java options you're running into the same issue you did before (`/tmp` forbids executable files). Can you report the logs when you do specify the temporary folder?

```python
import skein
client = skein.Client(java_options='-Djava.io.tmpdir=/path/to/tmp', log_level="debug")
```

This looks like the same issue as #181, which I've never been able to replicate. What version of `grpc` do you have installed? Did this issue start happening recently?

**Comment by quartox** [comment]
I haven't been using skein for a few months, so I created a new environment today with latest versions and this is the first I have seen it.

debug output:

```
19/07/29 14:21:25 DEBUG skein.Driver: Starting Skein version 0.7.4
19/07/29 14:21:25 DEBUG skein.Driver: Logging in using ticket cache
19/07/29 14:21:28 INFO skein.Driver: Driver started, listening on 44733
19/07/29 14:21:28 DEBUG skein.Driver: Reporting gRPC server port back to the launching process
E0729 14:21:28.110360544   67297 ssl_transport_security.cc:1229] Handshake failed with fatal error SSL_ERROR_SSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed.
19/07/29 14:21:28 DEBUG skein.Driver: Starting process disconnected, shutting down
19/07/29 14:21:28 DEBUG skein.Driver: Driver shut down
```

And I have `grpcio                    1.16.1           py37hf8bcb03_1` installed

**Comment by jcrist** [comment]
Hmmm, interesting. All your versions so far match things we test against. What version of Java, and OpenSSL? Can you try with grpcio 1.14 (available on conda and pypi) and/or grpcio 1.22 (currently pypi only).

**Comment by quartox** [comment]
Same issue with both versions of grpcio.

Java is the system installed java

```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```

OpenSSL is conda installed `openssl                   1.1.1c               h7b6447c_1`. Not sure if it is relevant but I have had some bugs with certificates in the past that required using the system installed curl instead of the conda install curl.

**Comment by jcrist** [comment]
Ok, last one. To ensure you're not using an old certificate, does this change anything:

```python
import skein
client = skein.Client(
    java_options='-Djava.io.tmpdir=/path/to/tmp',
    log_level="debug",
    security=skein.Security.new_credentials()
)
```

**Comment by quartox** [comment]
It works!

**Comment by jcrist** [comment]
Hooray! I assume you used this machine ~1 year ago with dask-yarn? We cache credentials on disk, and by default they expire after 365 days. I'm not sure what we should do about this (at worst we should at least error nicely).

**Comment by jcrist** [comment]
If you want to clear out the cache, you can do `skein gencerts --force`.

**Comment by quartox** [comment]
Yeah, I have jumped in and out of using dask-yarn on this cluster for about a year so that makes sense. Thanks!

**Comment by sephib** [comment]
> Hooray! I assume you used this machine ~1 year ago with dask-yarn? We cache credentials on disk, and by default they expire after 365 days. I'm not sure what we should do about this (at worst we should at least error nicely).

@jcrist we are having the same issue. 
we are using `skein 0.8.0` with `dask-yarn 0.7.0`  
when running `skein gencerts --force` we are getting an error 
>  argument command: invalid choice: 'gencerts'
  
what is the right solution for running with a `client` with  `dask-yarn`?

**Comment by jcrist** [comment]
Yeah, sorry, the command I posted above was incorrect (since updated). You should only need to run this once if the cached certs have expired. After that dask-yarn should work as normal.
