### ISSUE TITLE
Error running Driver - Can't get Kerberos realm despite setting the environment variables

### ISSUE THREAD

**Issue by mohamed-ali** [jcrist/skein#195]
Thanks for developing this useful tool!

I am not able to submit the "hello world" application due to kerberos error. Could you please have point me to what I missing? Thanks.

- **A description of the bug**

skein is complaining that it can't get `kerberos realm` despite that `kerberos` related environment variable are set. Here's the error:

```
ERROR skein.Driver: Error running Driver
java.lang.IllegalArgumentException: Can't get Kerberos realm
```

- **Steps to reproduce** 

I run the following script to configure environment variables and run skein hello world on the cluster. 

```bash
#!/bin/bash

export KRB5_CONFIG=location of krb5.conf
export HADOOP_OPTS=-Djava.security.krb5.conf=${KRB5_CONFIG}
kinit -kt ~/user.keytab user@realm
export JAVA_HOME={…java idk location…}
export HADOOP_HOME={…hadoop cli…}
export HADOOP_CONF_DIR={Hadoop conf}
export YARN_CONF_DIR={ …yarn conf…}
export HADOOP_JAAS_DEBUG=true
export KRB5CCNAME=/tmp/krb5cc_xxxx

hadoop fs -ls

skein application submit hello_world.yaml
```
The hello_world.yaml file contains the following:

```
name: hello_world
queue: default

master:
  resources:
    vcores: 1
    memory: 512 MiB
  script: |
    sleep 60
    echo "Hello World!"
```

Notice that I tried `hadoop fs -ls` with the same configuration and it works fine, but skein doesn't manage to run the helloworld example.

- **Relevant logs/tracebacks**

Error trace:

 ```
 ERROR skein.Driver: Error running Driver
java.lang.IllegalArgumentException: Can't get Kerberos realm
	at org.apache.hadoop.security.HadoopKerberosName.setConfiguration(HadoopKerberosName.java:65)
	at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:306)
	at org.apache.hadoop.security.UserGroupInformation.ensureInitialized(UserGroupInformation.java:291)
	at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:846)
	at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:816)
	at com.anaconda.skein.Driver.init(Driver.java:247)
	at com.anaconda.skein.Driver.main(Driver.java:174)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.hadoop.security.authentication.util.KerberosUtil.getDefaultRealm(KerberosUtil.java:88)
	at org.apache.hadoop.security.HadoopKerberosName.setConfiguration(HadoopKerberosName.java:63)
	... 6 more
Caused by: KrbException: Cannot locate default realm
	at sun.security.krb5.Config.getDefaultRealm(Config.java:1029)
	... 12 more
Error: Failed to start java process
sys:1: ResourceWarning: unclosed file <_io.BufferedWriter name=5>
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/user/.local/share/Virtualenvs/skein/lib/python3.6/site-packages/skein/core.py", line 491, in __del__
    self.close()
  File "/home/user/.local/share/Virtualenvs/skein/lib/python3.6/site-packages/skein/core.py", line 478, in close
    if self._proc is not None:
AttributeError: _proc
 ```

- **Version information**

    Please include version information for the following:

    - Python 3.6.9
    - Hadoop 2.7.3.2.6.xxx
    - skein==0.8.0

**Comment by jcrist** [comment]
I suspect this has to do with `HADOOP_OPTS` only affecting the hadoop CLI, not its underlying libraries. Try adding the following:

```
export SKEIN_DRIVER_JAVA_OPTIONS=-Djava.security.krb5.conf=${KRB5_CONFIG}
```

If using the python api, you can also set java options programmatically using the `java_options`kwarg: https://jcrist.github.io/skein/api.html#skein.Client.

**Comment by mohamed-ali** [comment]
@jcrist Thank you! That solved the problem.
