### ISSUE TITLE
java.net.BindException: Address already in use

### ISSUE THREAD

**Issue by Z0ltrix** [jcrist/skein#236]
- **A description of the bug**

We use nifi to do a kinit for kerberos auth and start an application via
```
#!/bin/bash
source /opt/miniforge/miniforge/envs/jupyterlab/bin/prologue.sh
skein application submit spec.yml
```

Our log said `java.net.BindException: Address already in use` but not really more... it looks like a new bug in skein 0.8.1 because we did not see this in 0.8.0

Any idea what the cause could be?

- **Steps to reproduce** 

See description.

- **Relevant logs/tracebacks**

Our YARN Job log looks like this.

```
21/11/12 15:32:23 INFO skein.ApplicationMaster: Starting Skein version 0.8.1
21/11/12 15:32:23 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
21/11/12 15:32:23 INFO skein.ApplicationMaster: Running as user nifi
21/11/12 15:32:23 INFO skein.ApplicationMaster: Application specification successfully loaded
21/11/12 15:32:24 INFO skein.ApplicationMaster: gRPC server started at xxxxxx:40069
21/11/12 15:32:24 WARN component.AbstractLifeCycle: FAILED ServerConnector@50cf5a23{HTTP/1.1}{0.0.0.0:0}: java.net.BindException: Address already in use
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:461)
	at sun.nio.ch.Net.bind(Net.java:453)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:222)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
	at com.anaconda.skein.shaded.org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
	at com.anaconda.skein.shaded.org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at com.anaconda.skein.shaded.org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at com.anaconda.skein.shaded.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.anaconda.skein.shaded.org.eclipse.jetty.server.Server.doStart(Server.java:366)
	at com.anaconda.skein.shaded.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.anaconda.skein.WebUI.start(WebUI.java:179)
	at com.anaconda.skein.ApplicationMaster.startUI(ApplicationMaster.java:373)
	at com.anaconda.skein.ApplicationMaster.run(ApplicationMaster.java:206)
	at com.anaconda.skein.ApplicationMaster.main(ApplicationMaster.java:171)
21/11/12 15:32:24 WARN component.AbstractLifeCycle: FAILED com.anaconda.skein.shaded.org.eclipse.jetty.server.Server@2899a8db: java.net.BindException: Address already in use
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:461)
	at sun.nio.ch.Net.bind(Net.java:453)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:222)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
	at com.anaconda.skein.shaded.org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
	at com.anaconda.skein.shaded.org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at com.anaconda.skein.shaded.org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at com.anaconda.skein.shaded.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.anaconda.skein.shaded.org.eclipse.jetty.server.Server.doStart(Server.java:366)
	at com.anaconda.skein.shaded.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.anaconda.skein.WebUI.start(WebUI.java:179)
	at com.anaconda.skein.ApplicationMaster.startUI(ApplicationMaster.java:373)
	at com.anaconda.skein.ApplicationMaster.run(ApplicationMaster.java:206)
	at com.anaconda.skein.ApplicationMaster.main(ApplicationMaster.java:171)
21/11/12 15:32:24 ERROR skein.ApplicationMaster: Shutting down: Unexpected error in application master
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:461)
	at sun.nio.ch.Net.bind(Net.java:453)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:222)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
	at com.anaconda.skein.shaded.org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
	at com.anaconda.skein.shaded.org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at com.anaconda.skein.shaded.org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at com.anaconda.skein.shaded.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.anaconda.skein.shaded.org.eclipse.jetty.server.Server.doStart(Server.java:366)
	at com.anaconda.skein.shaded.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.anaconda.skein.WebUI.start(WebUI.java:179)
	at com.anaconda.skein.ApplicationMaster.startUI(ApplicationMaster.java:373)
	at com.anaconda.skein.ApplicationMaster.run(ApplicationMaster.java:206)
	at com.anaconda.skein.ApplicationMaster.main(ApplicationMaster.java:171)
21/11/12 15:32:24 INFO skein.ApplicationMaster: Deleted application directory hdfs://xxxxx/user/nifi/.skein/application_1635856614720_2038
21/11/12 15:32:24 INFO skein.ApplicationMaster: WebUI server shut down
21/11/12 15:32:24 INFO skein.ApplicationMaster: gRPC server shut down

prelaunch.err0
prelaunch.out70Setting up env variables
Setting up job resources
Launching container
``` 

Our spec.yml looks like this:
``` 
master:
  env:
    ARROW_LIBHDFS_DIR: /opt/apache-hadoop/hadoop/lib/native/
    GIT_SSH_COMMAND: ssh -i ../sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
  log_level: INFO
  files:
    sshkey: hdfs:///teams/xxxx/git/sshkey
  resources:
    memory: 1
    vcores: 4096
  script: |
    source /opt/miniforge/miniforge/envs/jupyterlab/bin/prologue.sh
    git clone --branch aaaa bbbbb
    cd $(ls)
    bash entrypoint.sh
name: c32c748e-9dd7-4ac7-abff-a41ffae0fb09
queue: job
user: nifi
``` 

Our proloque.sh looks like this:
```
#!/bin/bash
export HOME=`pwd`/tmp
export PATH="/opt/apache-hadoop/hadoop/bin${PATH:+:${PATH}}"
export PATH="/opt/apache-spark/spark/bin${PATH:+:${PATH}}"
export PATH="/opt/apache-hbase/hbase/bin${PATH:+:${PATH}}"
export PATH="/opt/apache-drill/drill/bin${PATH:+:${PATH}}"
source /opt/apache-hadoop/hadoop/etc/hadoop/hadoop-env.sh
source /opt/apache-hadoop/hadoop/etc/hadoop/yarn-env.sh
source /opt/apache-spark/spark/conf/spark-env.sh
source /opt/apache-hbase/hbase/conf/hbase-env.sh
export PYSPARK_PYTHON=/opt/miniforge/miniforge/envs/jupyterlab/bin/python
source /opt/miniforge/miniforge/envs/jupyterlab/bin/activate
conda init bash

export KRB5CCNAME=$HOME/.krb_ticket_cache

cd $HOME

```

- **Version information**

    Please include version information for the following:

    - Python 3.7.9
    - Hadoop 2.9.2
    - Skein 0.8.1

Regards,
Christian

**Comment by Z0ltrix** [comment]
Seems to be a problem of the cloud instance... skein worked fine on other instances.

Sorry for the confusion.
