### ISSUE TITLE
`skein init` error on Python 2

### ISSUE THREAD

**Issue by hussainsultan** [jcrist/skein#9]
####Environment: 
```bash
(dev) hussainsultan@cluster-07d2-m:~$ which python
/home/hussainsultan/miniconda3/envs/dev/bin/python
(dev) hussainsultan@cluster-07d2-m:~$ /home/hussainsultan/miniconda3/envs/dev/bin/python
Python 2.7.15 | packaged by conda-forge | (default, May  8 2018, 14:46:53) 
```
error:
```bash
(dev) xx:~$ skein init
Unexpected Error:
Traceback (most recent call last):
  File "/home/hussainsultan/miniconda3/envs/dev/lib/python2.7/site-packages/skein/cli.py", line 262, in main
    func(**kwargs)
  File "/home/hussainsultan/miniconda3/envs/dev/lib/python2.7/site-packages/skein/cli.py", line 254, in entry_init
    Security.from_new_key_pair(force=force)
  File "/home/hussainsultan/miniconda3/envs/dev/lib/python2.7/site-packages/skein/core.py", line 110, in from_new_key_pair
    os.makedirs(directory, exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

```

**Comment by jcrist** [comment]
Yeah, I've spent zero effort so far on testing with python 2. Will try to fix over the next couple days.
